In [1]:
import pandas as pd # 판다스 import

df = pd.read_csv("../data/서울시 공공와이파이 서비스 위치 정보.csv", encoding="cp949")  # csv 파일 인코딩     
df

,관리번호,자치구,와이파이명,도로명주소,설치유형,설치기관,서비스구분,망종류,설치년도,실내외구분,Y좌표,X좌표,작업일자
0,24서울-0001,중구,서울시청 서소문제1청사,덕수궁길 15,4. 문화관광,디지털뉴딜(LG U+),공공WiFi,임대망,2024,실내,37.564327,126.97565,2026-09-08 03:00:12.948
1,24서울-0002,중구,서울시청 서소문제1청사,덕수궁길 15,4. 문화관광,디지털뉴딜(LG U+),공공WiFi,임대망,2024,실내,37.564327,126.97565,2026-09-08 03:00:12.948
2,24서울-0003,성동구,성동구청 송정동 공공복합청사,송정18가길 9,7-2-2. 공공 - 구의회 및 보건소,디지털뉴딜(LG U+),공공WiFi,임대망,2024,실내,37.554222,127.06895,2026-09-08 03:00:12.949
3,24서울-0004,성동구,성동구청 송정동 공공복합청사,송정18가길 9,7-2-2. 공공 - 구의회 및 보건소,디지털뉴딜(LG U+),공공WiFi,임대망,2024,실내,37.554222,127.06895,2026-09-08 03:00:12.949
4,24서울-0005,강동구,강동리본센터,강동구 양재대로81길 73,6-6. 복지 - 기타,디지털뉴딜(LG U+),공공WiFi,임대망,2024,실내,37.523857,127.13023,2026-09-08 03:00:12.95
...,...,...,...,...,...,...,...,...,...,...,...,...,...
26280,서울5차-1189,성동구,금남시장,서울특별시 성동구 장터5길 4-27,2. 전통시장,디지털뉴딜(LG U+),NaN,임대망,2023,실외,37.548610,127.02169,2026-09-08 03:00:14.103
26281,서울5차-1190,성동구,스마트쉼터(04107 청계벽산아파트_텐즈힐아파트),서울특별시 성동구 무학로 33,5-1. 버스정류소(국비),디지털뉴딜(LG U+),NaN,임대망,2023,실외,37.569130,127.02601,2026-09-08 03:00:14.103
26282,서울5차-1191,성동구,스마트쉼터(04295 황학교_텐즈힐몰),서울특별시 성동구 마장로 137,5-1. 버스정류소(국비),디지털뉴딜(LG U+),NaN,임대망,2023,실외,37.567776,127.02455,2026-09-08 03:00:14.103
26283,서울5차-1192,성동구,스마트쉼터(04212 성동세무서앞),서울특별시 성동구 광나루로 290,5-1. 버스정류소(국비),디지털뉴딜(LG U+),NaN,임대망,2023,실외,37.548000,127.06206,2026-09-08 03:00:14.103
26284,서울5차-1193,성동구,스마트쉼터(04236 뚝섬역8번출구),서울특별시 성동구 아차산로 6,5-1. 버스정류소(국비),디지털뉴딜(LG U+),NaN,임대망,2023,실외,37.547726,127.04552,2026-09-08 03:00:14.103

In [2]:
# 실내외 구분 결측치 체크
print(df.isna().sum())         

# ---------------------------------------------------------
# |  결측치 체크 결과 요약 (실내외 구분 이상 없음)         |
# ---------------------------------------------------------
# 관리번호       0
# 자치구        0
# 와이파이명      0
# 도로명주소    876
# 설치유형       0
# 설치기관       0
# 서비스구분    685
# 망종류        0
# 설치년도       0
# 실내외구분      0
# Y좌표        0
# X좌표        0
# 작업일자       0

관리번호       0
자치구        0
와이파이명      0
도로명주소    876
설치유형       0
설치기관       0
서비스구분    685
망종류        0
설치년도       0
실내외구분      0
Y좌표        0
X좌표        0
작업일자       0
dtype: int64

In [10]:
print("실외",  df.query(" 실내외구분 == '실외' ")["와이파이명"].count() )  
print("실내",  df.query(" 실내외구분 == '실내' ")["와이파이명"].count() )

실외 12982
실내 13303

In [36]:
#df.head()
#df.query(" 실내외구분 == '실외' ")[["자치구","도로명주소","Y좌표","X좌표"]]

#print("전체건수", len(df))  

# 실외인 걸 로 필터링
df_clean = df.query(" 실내외구분 == '실외' ")

df_clean["실내외구분"].unique()         # 실외 필터링 된 건수 확인
# <StringArray>
# ['실외']
# Length: 1, dtype: str

# 표시 위치 설정
df_clean["표시위치"] = df["도로명주소"].fillna(df["와이파이명"])
df_clean[["도로명주소","와이파이명","표시위치"]].reset_index()

# ---------------------------------------------------------
# |  도로명주소 가 있으면 도로명주소 로, 없으면 와아파이명 을 표시위치 로 설정 확인
# ---------------------------------------------------------
# 	index	도로명주소	    와이파이명	            표시위치
# 0	34	    NaN	          도림천 산책로2	       도림천 산책로2
# 1	143	    NaN	          도림천 산책로3	       도림천 산책로3
# 2	292	    NaN	          도림천 산책로4	       도림천 산책로4
# 3	323	    역삼동675-3	   버스정류소_KT강남지사	 역삼동675-3
# 4	324	    논현동261-1	   버스정류소_강남YMCA앞	 논현동261-1

,index,도로명주소,와이파이명,표시위치
0,34,NaN,도림천 산책로2,도림천 산책로2
1,143,NaN,도림천 산책로3,도림천 산책로3
2,292,NaN,도림천 산책로4,도림천 산책로4
3,323,역삼동675-3,버스정류소_KT강남지사,역삼동675-3
4,324,논현동261-1,버스정류소_강남YMCA앞,논현동261-1
...,...,...,...,...
12977,26280,서울특별시 성동구 장터5길 4-27,금남시장,서울특별시 성동구 장터5길 4-27
12978,26281,서울특별시 성동구 무학로 33,스마트쉼터(04107 청계벽산아파트_텐즈힐아파트),서울특별시 성동구 무학로 33
12979,26282,서울특별시 성동구 마장로 137,스마트쉼터(04295 황학교_텐즈힐몰),서울특별시 성동구 마장로 137
12980,26283,서울특별시 성동구 광나루로 290,스마트쉼터(04212 성동세무서앞),서울특별시 성동구 광나루로 290
12981,26284,서울특별시 성동구 아차산로 6,스마트쉼터(04236 뚝섬역8번출구),서울특별시 성동구 아차산로 6