### 가설검정의 원리
- 눈에 보이는 차이가 우연읹, 진짜인지를 판단하는 방법
- 용어
    - 귀무가설
    - 대립가설
    - 유의수준
    - p-value
- 따릉이 데이터의 남녀 이용차이로 검정절차를 확인해보기

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

plt.rcParams["font.family"] = "Malgun Gothic"   # 한글 깨짐 방지(윈도우 기본 폰트)
plt.rcParams["axes.unicode_minus"] = False

In [2]:
df = pd.read_csv("../data/07-9_bike_ttareungi.csv")
df

,대여일자,대여소번호,대여소명,대여구분코드,성별,연령대코드,이용건수,운동량,탄소량,이동거리(M),이용시간(분)
0,202606,1201,1201. 가락시장역 3번 출구,정기권,NaN,30대,123,8750.55,78.97,339960.75,2621
1,202606,5339,5339. 은빛1단지 아파트 앞,정기권,M,~10대,15,517.56,4.65,20107.79,173
2,202606,3928,3928.고척아이파크아파트 106동 앞,일일권,NaN,40대,7,444.12,4.00,17254.05,148
3,202606,102,102. 망원역 1번출구 앞,가족권(2시간),M,~10대,1,181.72,1.64,7060.00,66
4,202606,2265,2265. 이수고가차도 남단,일일권,F,50대,6,660.63,5.96,25665.78,220
...,...,...,...,...,...,...,...,...,...,...,...
4995,202606,4625,4625. 용산공원갤러리앞,일일권(3시간),M,20대,1,56.76,0.51,2205.05,148
4996,202606,239,239. 유스호스텔 앞,일일권(비회원),NaN,30대,1,NaN,NaN,0.00,7
4997,202606,3116,3116.신촌역 4번출구,정기권,M,50대,37,2183.44,19.42,83796.47,1639
4998,202606,281,281. 대림신동아아파트 앞,정기권,F,60대,18,429.06,3.91,16668.52,167
4999,202606,3890,3890. 웰츠타워 오피스텔,정기권,M,40대,170,8308.91,74.89,322874.15,3109

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 11 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   대여일자     5000 non-null   int64
 1   대여소번호    5000 non-null   int64
 2   대여소명     5000 non-null   str
 3   대여구분코드   5000 non-null   str
 4   성별       3188 non-null   str
 5   연령대코드    5000 non-null   str
 6   이용건수     5000 non-null   int64
 7   운동량      4992 non-null   float64
 8   탄소량      4992 non-null   float64
 9   이동거리(M)  5000 non-null   float64
 10  이용시간(분)  5000 non-null   int64
dtypes: float64(3), int64(4), str(4)
memory usage: 429.8 KB

In [4]:
df.isna().sum()

대여일자          0
대여소번호         0
대여소명          0
대여구분코드        0
성별         1812
연령대코드         0
이용건수          0
운동량           8
탄소량           8
이동거리(M)       0
이용시간(분)       0
dtype: int64

In [5]:
df_gender = df.dropna(subset=['성별'])
df_gender.isna().sum()

대여일자       0
대여소번호      0
대여소명       0
대여구분코드     0
성별         0
연령대코드      0
이용건수       0
운동량        2
탄소량        2
이동거리(M)    0
이용시간(분)    0
dtype: int64

In [26]:
male = df_gender.query(" 성별 == 'M' ")["이용건수"].sum()


fmale = df_gender.query(" 성별 == 'F' ")["이용건수"].sum()

In [10]:
df_gender.query(" 성별 == 'M' ")

,대여일자,대여소번호,대여소명,대여구분코드,성별,연령대코드,이용건수,운동량,탄소량,이동거리(M),이용시간(분)
1,202606,5339,5339. 은빛1단지 아파트 앞,정기권,M,~10대,15,517.56,4.65,20107.79,173
3,202606,102,102. 망원역 1번출구 앞,가족권(2시간),M,~10대,1,181.72,1.64,7060.00,66
5,202606,5766,5766. 북위례1,정기권,M,20대,26,749.83,6.74,30385.49,153
6,202606,4091,4091. 방학역2번출구,정기권,M,30대,207,13492.29,121.57,524177.51,4372
7,202606,3935,3935. 고대구로병원 앞,정기권,M,50대,116,5737.48,51.70,222901.18,2351
...,...,...,...,...,...,...,...,...,...,...,...
4988,202606,568,568. 청계8가 사거리 B,일일권,M,30대,68,5283.74,47.47,204512.36,1572
4991,202606,4045,4045. 은하수 공원,정기권,M,40대,11,1237.03,11.15,48058.71,400
4995,202606,4625,4625. 용산공원갤러리앞,일일권(3시간),M,20대,1,56.76,0.51,2205.05,148
4997,202606,3116,3116.신촌역 4번출구,정기권,M,50대,37,2183.44,19.42,83796.47,1639
4999,202606,3890,3890. 웰츠타워 오피스텔,정기권,M,40대,170,8308.91,74.89,322874.15,3109

In [12]:
df_gender.query(" 대여소번호 == 5339 ")

,대여일자,대여소번호,대여소명,대여구분코드,성별,연령대코드,이용건수,운동량,탄소량,이동거리(M),이용시간(분)
1,202606,5339,5339. 은빛1단지 아파트 앞,정기권,M,~10대,15,517.56,4.65,20107.79,173

In [14]:
df_gender.query(" 대여소번호 == 3116 ")

,대여일자,대여소번호,대여소명,대여구분코드,성별,연령대코드,이용건수,운동량,탄소량,이동거리(M),이용시간(분)
795,202606,3116,3116.신촌역 4번출구,일일권,M,~10대,4,612.82,5.64,24315.02,199
4997,202606,3116,3116.신촌역 4번출구,정기권,M,50대,37,2183.44,19.42,83796.47,1639

In [17]:
total_male = df_gender.query(" 성별 == 'M' ")["이용건수"].sum()
total_male

np.int64(83566)

np.int64(47247)

### 이 차이가 유의만한 차이이냐, 별거 아니야
- 귀무가설
    - 남녀의 전체 이용 건수가 같다
- 대립가설 
    - 남녀의 전체 이용 건수가 다르다.

### 유의수준과 p-value
- p-value : 귀무가설이 맞다고

In [19]:
male

np.int64(83566)

In [21]:
total_pmale

np.int64(47247)

In [27]:
from scipy import stats 
# t검정으로 
t,p = stats.ttest_ind(male, fmale, equal_var=False)

print(t, "t통계량")
print(f"{p:4f}","p-value")

nan t통계량
 nan p-value

### 내판단이 틀릴 수도 있다
- 1종 오류
    - 사실은 차이가 없는데 있다고 잘못 판단
- 2종 오류
    - 사실은 차이가

### t검정
- 가장 자주 만다는 질문 : 두 그룹의 평균이 다른가? 라는 질문
- 가장 기본적인 판단 기준

- 일표본 : 한 그룹의 평균이 특정 기준과 다른가?
    - 예) 평균 이용 시간이 70분과 다른가?
- 독립표본 : 서로 다른 두 그룹 비교
    - 남성과 여성
- 대응표본: 같은 대상의 두 조건 비교
    - 같은 상권의 주중 vs 주말

### 1.일표본 t검정 -

In [30]:
t,p =  stats.ttest_1samp(df_gender['이용건수'], 40)
print("평균 이용 건수", df_gender['이용건수'].mean())
print(p)

평균 이용 건수 41.03293601003764
0.4504400827223802

In [31]:
df_gender.head(3)

,대여일자,대여소번호,대여소명,대여구분코드,성별,연령대코드,이용건수,운동량,탄소량,이동거리(M),이용시간(분)
1,202606,5339,5339. 은빛1단지 아파트 앞,정기권,M,~10대,15,517.56,4.65,20107.79,173
3,202606,102,102. 망원역 1번출구 앞,가족권(2시간),M,~10대,1,181.72,1.64,7060.00,66
4,202606,2265,2265. 이수고가차도 남단,일일권,F,50대,6,660.63,5.96,25665.78,220

In [32]:
df_gender['이용시간(분)/건별'] = (df_gender['이용시간(분)'] / df_gender['이용건수']).round(2)
df_gender.head(3)

,대여일자,대여소번호,대여소명,대여구분코드,성별,연령대코드,이용건수,운동량,탄소량,이동거리(M),이용시간(분),이용시간(분)/건별
1,202606,5339,5339. 은빛1단지 아파트 앞,정기권,M,~10대,15,517.56,4.65,20107.79,173,11.53
3,202606,102,102. 망원역 1번출구 앞,가족권(2시간),M,~10대,1,181.72,1.64,7060.00,66,66.00
4,202606,2265,2265. 이수고가차도 남단,일일권,F,50대,6,660.63,5.96,25665.78,220,36.67

In [34]:
male_time = df_gender.query(" 성별 == 'M' ")['이용시간(분)/건별']
print(male_time)

fmale_time = df_gender.query(" 성별 == 'F' ")['이용시간(분)/건별']
print(fmale_time)

1        11.53
3        66.00
5         5.88
6        21.12
7        20.27
         ...
4988     23.12
4991     36.36
4995    148.00
4997     44.30
4999     18.29
Name: 이용시간(분)/건별, Length: 1682, dtype: float64
4       36.67
10      20.85
12      10.00
15      35.64
27      64.50
        ...
4987    28.97
4990    16.21
4992    24.75
4993    25.67
4998     9.28
Name: 이용시간(분)/건별, Length: 1506, dtype: float64

In [38]:
t, p = stats.ttest_ind(male_time, fmale_time, equal_var=False)

print(f"남자평균 {male_time.mean():.2f}") 
print(f"여자평균 {fmale_time.mean():.2f}") 
print("p-value",p)

남자평균 29.97
여자평균 31.72
p-value 0.11720961663237059